# BACKEND/.nixpacks.toml
[phases.setup]
cmds = ["apt-get update && apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev libzip-dev"]
pkgs = ["php", "nginx", "libmysqlclient", "phpPackages.composer"]
# SIN nodejs, SIN npm

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = ["php artisan optimize"]

[start]
cmd = "php artisan migrate --force && php artisan storage:link && php artisan optimize:clear && php -S 0.0.0.0:$PORT -t public"

[variables]
PORT = "8080"